### ISSUE TITLE
Auto encoders

### ISSUE THREAD

**Issue by rmlopes** [itdxer/neupy#123]
Just to be sure, in the auto encoder example ([cutting layers](http://neupy.com/docs/surgery.html#cutting-layers-from-the-network)), the encoder weights will not be updated, only the weights associated with the SoftMax layer introduced at the end?

When one cuts layers, can we do something like:
`algorithms.Momentum(aecut).predict(data)` in order to generate the features encoded in the auto encoder (I have trained the AE with momentum, but actually any algorithm should be able to provide the `predict` result)?

**Comment by itdxer** [comment]
When you cut layers from network you just copy them and then use in some other networks. Layers from the previous network should work in exactly the same way as before.

**Comment by itdxer** [comment]
And yes in that case
```
algorithms.Momentum(aecut).predict(data)
```
any algorithm should work in exactly the same way

**Comment by itdxer** [comment]
One important note is that you can also use it with Theano, without NN trainign algorithms. It can be something like this

```python
>>> from neupy import algorithms, layers
>>> autoencoder = algorithms.Momentum(
...     [
...         layers.Input(784),
...         layers.Sigmoid(100),
...         layers.Sigmoid(784),
...     ],
...     step=0.1,
...     momentum=0.99,
...     verbose=True,
...     error='rmse',
... )
Main information

[ALGORITHM] Momentum

[OPTION] batch_size = 128
[OPTION] verbose = True
[OPTION] epoch_end_signal = None
[OPTION] show_epoch = 1
[OPTION] shuffle_data = False
[OPTION] step = 0.1
[OPTION] train_end_signal = None
[OPTION] error = rmse
[OPTION] addons = None
[OPTION] momentum = 0.99
[OPTION] nesterov = False

[THEANO] Initializing Theano variables and functions.
[THEANO] Initialization finished sucessfully. It took 2.72 seconds
>>>
>>>
>>> from neupy import surgery
>>> encoder = surgery.cut(autoencoder, start=0, end=2)
>>> encoder
Input(784) > Sigmoid(100)
>>>
>>> x = T.matrix('x')
>>> y = encoder.output(x)
>>>
>>> import theano
>>> f = theano.function([x], y)
>>> 
>>> import numpy as np
>>> data = np.random.randn(1000, 784)
>>> data.shape
(1000, 784)
>>> t = f(data)
>>> t.shape
(1000, 100)
```

**Comment by rmlopes** [comment]
Another related question, how is mse calculated for multiple outputs? (you can point me to the related code please)

I ask this because I just opened the features generated by a compressing autoencoder (4 feat. to 2) whose error was still decreasing, and the output of the two neurons is always 1. This seems odd, and in the meanwhile I will try to put the example online so that I can show exactly what I mean.

**Comment by itdxer** [comment]
All error functions are in [neupy/network/errors.py](https://github.com/itdxer/neupy/blob/master/neupy/network/errors.py#L27). MSE is just an average overall squared differences between expected and predicted values per each sample and feature.
