### ISSUE TITLE
How to get the parameters for each layer?

### ISSUE THREAD

**Issue by pswpswpsw** [itdxer/neupy#158]

**Comment by itdxer** [comment]
Do you mean something like this?

```python
>>> from neupy.layers.utils import iter_parameters
>>>
>>> network = layers.join(
...     layers.Input(1),
...     layers.Sigmoid(2),
...     layers.Sigmoid(3),
... )
>>>
>>> print(network)
Input(1) > Sigmoid(2) > Sigmoid(3)
>>> for layer, attrname, parameter in iter_parameters(network):
...     # parameter is shared Theano variable
...     parameter_value = parameter.get_value()
...     print("Layer: {}".format(layer))
...     print("Parameter name: {}".format(attrname))
...     print("Parameter shape: {}".format(parameter_value.shape))
...     print()
...
Layer: Sigmoid(2)
Parameter name: weight
Parameter shape: (1, 2)

Layer: Sigmoid(2)
Parameter name: bias
Parameter shape: (2,)

Layer: Sigmoid(3)
Parameter name: weight
Parameter shape: (2, 3)

Layer: Sigmoid(3)
Parameter name: bias
Parameter shape: (3,)
```

**Comment by pswpswpsw** [comment]
I got it! Thank you! I need this because I want to train a deep autoencoder with pretraining techniques.. My current data is very hard to train and always fail in local minima. I tried tensorflow and keras, and this library as well, particularly for better optimizer, but it seems that only pretraining is my hope.

If network is not layer but a network algo, then network.layers will work instead.

from neupy.layers.utils import iter_parameters
for layer, attrname, parameter in iter_parameters(network.layers):
    parameter_value = parameter.get_value()
    print parameter_value.shape

**Comment by itdxer** [comment]
In case if you are pretraining weight and bias parameter, then you can directly access them from the layer

```python
from neupy import layers

input_layer = layers.Input(10)
output_layer = layers.Sigmoid(5)

network = input_layer > output_layer

weight = output_layer.weight.get_value()
bias = output_layer.bias.get_value()
```

Also you can pretrain parts of the network and then reuse this parts later. In this way you will not need to make direct access to the parameters. Check [this example](https://github.com/itdxer/neupy/blob/master/examples/autoencoder/stacked_conv_autoencoders.py). It shows how to build a network with pretrained layers.

**Comment by itdxer** [comment]
@pswpswpsw Did it help you to solve your problem?
