### ISSUE TITLE
ImportError theano

### ISSUE THREAD

**Issue by fguimara** [itdxer/neupy#174]
Trying to install neupy

from neupy import algorithms

> ImportError                               Traceback (most recent call last)
> <ipython-input-96-f3f31c65dc64> in <module>()
> ----> 1 from neupy import algorithms
>       2 
>       3 
> 
> /home/fferreira/.virtualenvs/blend/local/lib/python2.7/site-packages/neupy/algorithms/__init__.py in <module>()
>       1 # Algorithms
> ----> 2 from .gd.base import *
>       3 from .gd.lev_marq import *
>       4 from .gd.quasi_newton import *
>       5 from .gd.conjgrad import *
> 
> /home/fferreira/.virtualenvs/blend/local/lib/python2.7/site-packages/neupy/algorithms/gd/base.py in <module>()
>       5 
>       6 import six
> ----> 7 import theano
>       8 import theano.tensor as T
>       9 import numpy as np
> 
> /home/fferreira/.virtualenvs/blend/local/lib/python2.7/site-packages/theano/__init__.py in <module>()
>      74 from theano.printing import pprint, pp
>      75 
> ---> 76 from theano.scan_module import scan, map, reduce, foldl, foldr, clone
>      77 
>      78 from theano.updates import OrderedUpdates
> 
> /home/fferreira/.virtualenvs/blend/local/lib/python2.7/site-packages/theano/scan_module/__init__.py in <module>()
>      38 __contact__ = "Razvan Pascanu <r.pascanu@gmail>"
>      39 
> ---> 40 from theano.scan_module import scan_opt
>      41 from theano.scan_module.scan import scan
>      42 from theano.scan_module.scan_views import map, reduce, foldl, foldr
> 
> /home/fferreira/.virtualenvs/blend/local/lib/python2.7/site-packages/theano/scan_module/scan_opt.py in <module>()
>      57 
>      58 import theano
> ---> 59 from theano import tensor, scalar
>      60 from theano.tensor import opt, get_scalar_constant_value, Alloc, AllocEmpty
>      61 from theano import gof
> 
> /home/fferreira/.virtualenvs/blend/local/lib/python2.7/site-packages/theano/tensor/__init__.py in <module>()
>      11     TensorConstantSignature, TensorConstant)
>      12 
> ---> 13 from theano.tensor import opt
>      14 from theano.tensor import opt_uncanonicalize
>      15 from theano.tensor import blas
> 
> ImportError: cannot import name opt
> 

pip freeze

> backports-abc==0.5
> backports.shutil-get-terminal-size==1.0.0
> bleach==1.5.0
> -e git+ssh://git@bitbucket.org/blendlps/blend_utils.git@e318f73c6232b9e9205e0db6fad510a3355109a2#egg=blend_utils
> certifi==2016.9.26
> configparser==3.5.0
> cycler==0.10.0
> Cython==0.25.2
> decorator==4.0.10
> entrypoints==0.2.2
> enum34==1.1.6
> funcsigs==1.0.2
> functools32==3.2.3.post2
> graphviz==0.5.1
> html5lib==0.9999999
> inspyred==1.0.1
> ipykernel==4.5.2
> ipython==5.1.0
> ipython-genutils==0.1.0
> ipywidgets==5.1.3
> Jinja2==2.9.4
> joblib==0.10.3
> jsonschema==2.5.1
> jupyter==1.0.0
> jupyter-client==4.4.0
> jupyter-console==5.0.0
> jupyter-contrib-core==0.3.0
> jupyter-contrib-nbextensions==0.2.3
> jupyter-core==4.2.1
> jupyter-highlight-selected-word==0.0.7
> jupyter-latex-envs==1.3.6
> jupyter-nbextensions-configurator==0.2.2
> Mako==1.0.6
> MarkupSafe==0.23
> matplotlib==1.5.3
> mistune==0.7.3
> mock==1.3.0
> nbconvert==5.0.0
> nbformat==4.2.0
> neupy==0.5.1
> nimfa==1.3.2
> nose==1.3.7
> nose-parameterized==0.5.0
> notebook==4.3.1
> numpy==1.12.1
> pandas==0.19.2
> pandocfilters==1.4.1
> paretochart==1.0
> path.py==8.1.2
> pathlib2==2.2.0
> patsy==0.4.1
> pbr==1.10.0
> pexpect==4.2.1
> pickleshare==0.7.4
> pkg-resources==0.0.0
> prompt-toolkit==1.0.9
> psutil==5.0.1
> ptyprocess==0.5.1
> pydot==1.0.2
> Pygments==2.1.3
> pygpu==0.6.2
> pyparsing==2.1.10
> python-dateutil==2.6.0
> pytz==2016.10
> PyYAML==3.12
> pyzmq==16.0.2
> qgrid==0.3.2
> qtconsole==4.2.1
> rpy2==2.8.5
> rvenv==0.2
> scandir==1.4
> -e git+git@github.com:fguimara/scikit-learn.git@254d7fbfdcfdce9c12558153324f37aed82f79e4#egg=scikit_learn
> scipy==0.19.0
> seaborn==0.7.1
> simplegeneric==0.8.1
> singledispatch==3.4.0.3
> six==1.10.0
> statsmodels==0.6.1
> terminado==0.6
> testpath==0.3
> Theano==0.8.2
> tornado==4.4.2
> traitlets==4.3.1
> wcwidth==0.1.7
> widgetsnbextension==1.2.2
> xgboost==0.6a2
> xlrd==0.9.4
> xlwt==1.0.0

**Comment by fguimara** [comment]
Nevermind... rebooted the jupyter kernel and it worked...

**Comment by itdxer** [comment]
It really looks like a temporary problem, since everything is fine with versions and Theano has module `opt` in the 0.8.2 (`from theano.tensor import opt`).
