### ISSUE TITLE
L1 and L2 regularization

### ISSUE THREAD

**Issue by Code1983** [itdxer/neupy#176]
I wasn't sure if L1 and L2 regularization methods were present.

**Comment by itdxer** [comment]
It has L2 regularization aka Weight decay: http://neupy.com/apidocs/neupy.algorithms.regularization.weight_decay.html#neupy.algorithms.regularization.weight_decay.WeightDecay
And there is the L-inf normalization aka Max-norm regularization: http://neupy.com/apidocs/neupy.algorithms.regularization.max_norm.html#neupy.algorithms.regularization.max_norm.MaxNormRegularization

There is no L1 regularization in NeuPy

**Comment by Code1983** [comment]
Thanks a lot.
