### ISSUE TITLE
Pickle file of trained model

### ISSUE THREAD

**Issue by AkshayTharval** [itdxer/neupy#187]
In the documentation it is mentioned that the pickle file will be in the following format 
![neupy](https://user-images.githubusercontent.com/16597923/28932569-f4b79e8e-7847-11e7-9636-b48158ef553d.PNG)

but when I opened the pickle file in Atom to visualize the weight and bias of the trained model, the text in the file is not what it should be. Should I open the file in another editor? I want to see the parameters of the trained model as mentioned in the documentation (pic above).

**Comment by itdxer** [comment]
Hm, I think that documentation can be a bit misleading. Pickle is a binary protocol and parameters are stored in the binary format. If you want to save as a plain text - then you need to read the parameters with `pickle.load` and save them in some other format, for instance in json.

Also, current format is to simple and not flexible. In the next neupy version I prepared new format for it. In addition it would be possible to store in HDF5 format as well (in case if it would be more familiar to you)

**Comment by AkshayTharval** [comment]
Doesn't matter if I save it in JSON format. It still shows me the same thing.
If not in the same format as given in the documentation, is it possible for me to extract the weights and biases of each layer of trained model?

**Comment by itdxer** [comment]
Did you try it like this?

```python
In [1]: import neupy

In [2]: neupy.__version__
Out[2]: '0.5.2'

In [3]: from neupy.layers import *

In [4]: conn = Input(2) > Sigmoid(3) > Sigmoid(1)

In [5]: from neupy import storage

In [6]: storage.save(conn, 'test.pickle')

In [7]: import pickle

In [8]: with open('test.pickle', 'rb') as f:
   ...:     parameters = pickle.load(f)
   ...:

In [9]: parameters.keys()
Out[9]: ['sigmoid-2', 'sigmoid-1']

In [10]: parameters['sigmoid-1']
Out[10]:
{'bias': array([ 0.,  0.,  0.]),
 'weight': array([[ 0.7640469 , -0.03213958,  1.64706842],
        [-0.25511324, -0.16131437,  0.96425316]])}

In [11]: parameters['sigmoid-2']
Out[11]:
{'bias': array([ 0.]), 'weight': array([[ 0.73364236],
        [ 1.23405536],
        [-0.155646  ]])}

In [12]: parameters['sigmoid-2']['weight']
Out[12]:
array([[ 0.73364236],
       [ 1.23405536],
       [-0.155646  ]])
```

**Comment by itdxer** [comment]
Also you can get parameters like this

```python
In [14]: conn.layer('sigmoid-1').weight.get_value()
Out[14]:
array([[ 0.7640469 , -0.03213958,  1.64706842],
       [-0.25511324, -0.16131437,  0.96425316]])

In [15]: conn.layer('sigmoid-1').bias.get_value()
Out[15]: array([ 0.,  0.,  0.])
```

or like this

```python
In [18]: for layer in conn:
    ...:     print(layer.name)
    ...:     if layer.parameters:  # `parameters` is a dictionary with parameters
    ...:         print(layer.weight.get_value())
    ...:         print(layer.bias.get_value())
    ...:     print('-----')
    ...:
input-1
-----
sigmoid-1
[[ 0.7640469  -0.03213958  1.64706842]
 [-0.25511324 -0.16131437  0.96425316]]
[ 0.  0.  0.]
-----
sigmoid-2
[[ 0.73364236]
 [ 1.23405536]
 [-0.155646  ]]
[ 0.]
-----
```

**Comment by AkshayTharval** [comment]
Awesome! That works perfect! Thank you! Big help!
