### ISSUE TITLE
Bug in hyperparameter optimization example

### ISSUE THREAD

**Issue by severinsimmler** [itdxer/neupy#192]
Great library, but I found a bug in your [Bayesian hyperparameter optimization example](http://neupy.com/2016/12/17/hyperparameter_optimization_for_neural_networks.html#find-number-of-hidden-units).

The function `hyperparam_selection` throws the error:

```
AttributeError: module 'random' has no attribute 'ranint'
```

I think you forgot the `d` in `random.ranint(min_n_hidden, max_n_hidden)`. Works just fine with `random.randint`.

**Comment by itdxer** [comment]
Thank you for reporting! I will fix it asap.

**Comment by itdxer** [comment]
Fixed: http://neupy.com/2016/12/17/hyperparameter_optimization_for_neural_networks.html
