### ISSUE TITLE
AttributeError: module 'neupy' has no attribute 'DiscreteHopfieldNetwork'

### ISSUE THREAD

**Issue by Agyolchu** [itdxer/neupy#193]
Hi, When I run my code I got an error that there is no attribute with the name of `DiscreteHopfieldNetwork`. I use python3.5. I would like to know why I get this error. Thank you for reading.

**Comment by itdxer** [comment]
Hi,
What neupy version do you use? (my version is 0.6.0)

```
In [1]: import neupy

In [2]: neupy.DiscreteHopfieldNetwork
...
AttributeError: 'module' object has no attribute 'DiscreteHopfieldNetwork'

In [3]: from neupy import algorithms

In [4]: algorithms.DiscreteHopfieldNetwork
Out[4]: neupy.algorithms.memory.discrete_hopfield_network.DiscreteHopfieldNetwork
```

Do you import it in the same way?

**Comment by Agyolchu** [comment]
Hi Solved thank you so much
