### ISSUE TITLE
neupy install in armbian killed in 99%

### ISSUE THREAD

**Issue by Trochez** [itdxer/neupy#194]
try install neupy in pi zero board with armbian but this installation killed in 99%

**Comment by itdxer** [comment]
did you get some errors or warnings during installation?

**Comment by Trochez** [comment]
no, just says killed and aborts installation

**Comment by itdxer** [comment]
neupy is purely python library, there shouldn't be anything that breaks installation. Do you have enough memory on your device? Also, it's possible that some of the neupy's dependencies break your installation like Theano, numpy, scipy or matplotlib. Can you also check that you can install manually each of these dependencies one by one?
https://github.com/itdxer/neupy/blob/master/requirements/main.txt

**Comment by Trochez** [comment]
I found a solution, after consult many blogs, I make some steps to solved it, I think the problem was there wasn't some dependencies and device space.
The steps that I made:
1-apt-get install libpython2.7-dev python-numpy
2-install pystan(python install)
3-apt-get install pkg-config
4-install gfortran(apt-get)
5-sudo apt-get install libblas-dev liblapack-dev
6-umount -l /tmp
7-clone a project and install it from a source code
