### ISSUE TITLE
Training Stop when Adam optimzer is used in Neupy

### ISSUE THREAD

**Issue by EdwinGerman** [itdxer/neupy#199]
Hello, Dears, I am using NeuPy to train a neural network with Adam but I have some problems when the training is performed. The code and the error are shown below. The database is also uploaded. I will appreciate your help to solve this issue.

Thanks.

**The code:**
```
[fisa_casp3_full.csv.gz](https://github.com/itdxer/neupy/files/1588249/fisa_casp3_full.csv.gz)

from neupy.exceptions import StopTraining
from neupy import algorithms, layers, storage
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from neupy import plots
import pandas as pd
import  math



def average(x):
    assert len(x) > 0
    return float(sum(x)) / len(x)

def pearson_def(x, y):
    assert len(x) == len(y)
    n = len(x)
    assert n > 0
    avg_x = average(x)
    avg_y = average(y)
    diffprod = 0
    xdiff2 = 0
    ydiff2 = 0
    for idx in range(n):
        xdiff = x[idx] - avg_x
        ydiff = y[idx] - avg_y
        diffprod += xdiff * ydiff
        xdiff2 += xdiff * xdiff
        ydiff2 += ydiff * ydiff

    return diffprod / math.sqrt(xdiff2 * ydiff2)
percentaje_test = 0.10

full_dataset = pd.read_csv("fisa_casp3_full.csv")


full_dt_rows = full_dataset.shape[0]
n_rows_train = full_dt_rows - int(full_dt_rows*percentaje_test)
n_cols_train = full_dataset.shape[1]


x_train_dataset      = full_dataset.ix[0:n_rows_train,0:n_cols_train-1].reset_index(drop=True)
y_train_dataset      = full_dataset.ix[0:n_rows_train,n_cols_train-1].reset_index(drop=True)

x_scaler             = preprocessing.RobustScaler().fit(x_train_dataset)
y_scaler             = preprocessing.StandardScaler().fit(y_train_dataset.values.reshape(-1, 1))

x_train_scaled       = x_scaler.transform(x_train_dataset)
y_train_scaled       = y_scaler.transform(y_train_dataset.values.reshape(-1, 1))

x_test_dataset       = full_dataset.ix[n_rows_train:full_dataset.shape[0],0:n_cols_train-1].reset_index(drop=True)
y_test_dataset       = full_dataset.ix[n_rows_train:full_dataset.shape[0],n_cols_train-1].reset_index(drop=True)

x_test_scaled        = x_scaler.transform(x_test_dataset)

adamnet = algorithms.Adam(
         [layers.Input(x_train_scaled.shape[1]),
         layers.Tanh(20),
         layers.Linear(1),],
         shuffle_data = True,
         batch_size=250,
         verbose=True,
         show_epoch=1,
         epsilon=1e-8,
     )

for exp in range(0,10):
    x_train, x_val, y_train, y_val = train_test_split(
        x_train_scaled, y_train_scaled, train_size=0.90, shuffle=True,
    )
    adamnet.train(x_train, y_train, x_val, y_val, epochs=30000)

plots.error_plot(adamnet)

y_predicted = adamnet.predict(x_test_scaled)
y_predicted_denorm = y_scaler.inverse_transform(y_predicted)


R1 = pearson_def(y_predicted_denorm, y_test_dataset)

print(R1)


```
**The Error:**

File "ToolNN.py", line 259, in <module>
    adamnet.train(x_train, y_train, x_val, y_val, epochs=30000)
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/neupy/algorithms/constructor.py", line 500, in train
    *args, **kwargs
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/neupy/algorithms/base.py", line 412, in train
    target_test)
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/neupy/algorithms/gd/base.py", line 528, in prediction_error
    show_error_output=True,
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/neupy/algorithms/gd/base.py", line 414, in apply_batches
    show_error_output=show_error_output,
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/neupy/algorithms/gd/base.py", line 281, in apply_batches
    bar.update(0)
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 528, in update
    self.start()
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 618, in start
    self.update(self.min_value, force=True)
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 565, in update
    StdRedirectMixin.update(self, value=value)
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 130, in update
    self.fd.write('\r' + ' ' * self.term_width + '\r')
IOError: [Errno 4] Interrupted system call

**Comment by itdxer** [comment]
Hi,
Could you try to set up parameter `show_epoch=2` or if it won't work then `verbose=False`?

**Comment by EdwinGerman** [comment]
Thank you very much, I try with show_epoch=25, this solves the problem.
