### ISSUE TITLE
Can't use gpu option when Adam optimizer is used in neural network.

### ISSUE THREAD

**Issue by EdwinGerman** [itdxer/neupy#200]
Hello, Dears I am using Adam to train a basic neural network model. When I train it using in CPU all is ok. On the other hand, when I try to train the same model with GPU an error occurs. I am sending the code and the error.

**To use the GPU, I put in the terminal: THEANO_FLAGS="device=cuda0" python ToolNN.py**

Thank you very much.

**The code:**
```
from neupy.exceptions import StopTraining
from neupy import algorithms, layers, storage
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from neupy import plots
import pandas as pd
import  math

def average(x):
    assert len(x) > 0
    return float(sum(x)) / len(x)

def pearson_def(x, y):
    assert len(x) == len(y)
    n = len(x)
    assert n > 0
    avg_x = average(x)
    avg_y = average(y)
    diffprod = 0
    xdiff2 = 0
    ydiff2 = 0
    for idx in range(n):
        xdiff = x[idx] - avg_x
        ydiff = y[idx] - avg_y
        diffprod += xdiff * ydiff
        xdiff2 += xdiff * xdiff
        ydiff2 += ydiff * ydiff

    return diffprod / math.sqrt(xdiff2 * ydiff2)
full_dataset = pd.read_csv("fisa_casp3_full_non_duplicate2.csv")
full_dt_rows = full_dataset.shape[0]
n_rows_train = full_dt_rows - int(full_dt_rows*percentaje_test)
n_cols_train = full_dataset.shape[1]


x_train_dataset      = full_dataset.ix[0:n_rows_train,0:n_cols_train-1].reset_index(drop=True)
y_train_dataset      = full_dataset.ix[0:n_rows_train,n_cols_train-1].reset_index(drop=True)

x_scaler             = preprocessing.RobustScaler().fit(x_train_dataset)
y_scaler             = preprocessing.StandardScaler().fit(y_train_dataset.values.reshape(-1, 1))

x_train_scaled       = x_scaler.transform(x_train_dataset)
y_train_scaled       = y_scaler.transform(y_train_dataset.values.reshape(-1, 1))
x_test_dataset       = full_dataset.ix[n_rows_train:full_dataset.shape[0],0:n_cols_train-1].reset_index(drop=True)
y_test_dataset       = full_dataset.ix[n_rows_train:full_dataset.shape[0],n_cols_train-1].reset_index(drop=True)

x_test_scaled        = x_scaler.transform(x_test_dataset)
adamnet = algorithms.Adam(
         [layers.Input(x_train_scaled.shape[1]),
         layers.Tanh(15),
         layers.Dropout(0.1),
         layers.Tanh(15),
         layers.Dropout(0.1),
         layers.Linear(1),],
         shuffle_data = True,
         batch_size=500,
         verbose=True,
         show_epoch=100,
         epsilon=1e-8,
     )
x_train, x_val, y_train, y_val = train_test_split(
    x_train_scaled, y_train_scaled, train_size=0.90, shuffle=True,
)
adamnet.train(x_train, y_train, x_val, y_val, epochs=530000)

plots.error_plot(adamnet)

y_predicted = adamnet.predict(x_test_scaled)
y_predicted_denorm = y_scaler.inverse_transform(y_predicted)


R1 = pearson_def(y_predicted_denorm, y_test_dataset)

print(R1)
```
**The error:**
[THEANO] Initializing Theano variables and functions.
Traceback (most recent call last):
  File "ToolNN.py", line 236, in <module>
    epsilon=1e-8,
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/neupy/algorithms/gd/base.py", line 113, in __init__
    super(GradientDescent, self).__init__(connection, **options)
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/neupy/algorithms/constructor.py", line 291, in __init__
    super(ConstructibleNetwork, self).__init__(*args, **kwargs)
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/neupy/algorithms/constructor.py", line 163, in __init__
    self.init_methods()
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/neupy/algorithms/constructor.py", line 341, in init_methods
    updates=self.init_train_updates(),
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/neupy/algorithms/constructor.py", line 358, in init_train_updates
    updates.extend(self.init_param_updates(layer, parameter))
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/neupy/algorithms/gd/adam.py", line 88, in init_param_updates
    step = asfloat(self.variables.step)
  File "/home/edwin/anaconda2/lib/python2.7/site-packages/neupy/utils.py", line 103, in asfloat
    return float_x_type(value)
  File "/home/edwin/.local/lib/python2.7/site-packages/numpy/core/numerictypes.py", line 860, in <lambda>
    cast[key] = lambda x, k=key: array(x, copy=False).astype(k)
ValueError: setting an array element with a sequence.

**Comment by itdxer** [comment]
Hi,
Can you check if the same error happens with another algorithm? For example with `Adamax` or `Adagrad`. If you just replace part of the code where `algorithms.Adam` to `algorithms.Adamax` it should work

Adagrad doc - http://neupy.com/apidocs/neupy.algorithms.gd.adagrad.html#neupy.algorithms.gd.adagrad.Adagrad
Adamax doc - http://neupy.com/apidocs/neupy.algorithms.gd.adamax.html#neupy.algorithms.gd.adamax.Adamax

**Comment by EdwinGerman** [comment]
Thank you for your response. Now is working with Adamax. Do you know any insight about the difference between Adam and Adamax?

Thank you very much.

**Comment by itdxer** [comment]
Thank you for checking, that's definitely some problem with Adam algorithm implementation. I will try to fix for the next release and I will let you know when patch will be available.

> Do you have any insight about the difference between Adam and Adamax?

These two algorithms are very similar. The only difference is the way they [normalize moments](https://en.wikipedia.org/wiki/Moment_(mathematics)#Normalised_moments). I think that this article gives good short explanation: http://ruder.io/optimizing-gradient-descent/index.html#adam

**Comment by itdxer** [comment]
You can try to install fix from https://github.com/itdxer/neupy/tree/release/v0.6.3 and check if Adam is still failing for you

**Comment by EdwinGerman** [comment]
Thank you very much for the insights. I update NeuPy and then I run Adam without problems. But I see that the performance obtained by Adamax is better than Adam. So I am using Adamax for my final model.

Thanks a lot for your help.
