### ISSUE TITLE
Weight and Bias values after training

### ISSUE THREAD

**Issue by jjihoon** [itdxer/neupy#206]
Hi,

So, I trained data based on the following condition:

cgnet = algorithms.Momentum(
    connection=[
        layers.Input(3), 
        layers.Sigmoid(4),
        layers.Sigmoid(1),
    ],
    step=0.6,
    shuffle_data=True,
    show_epoch=100,
    train_end_signal=print_epoch_weight,
    verbose=True,
)

If you see the code above, there is a function called "print_epoch_weight," which prints out weight and bias values after training is finished. And, training several times, I found out that the algorithm does not print out the same values of weight and bias. So I wonder how come the values change every time I train the algorithm.

**Comment by itdxer** [comment]
You can learn more about "symmetry breaking" problem in MIT deep learning book, section 8.4: http://www.deeplearningbook.org/contents/optimization.html
