### ISSUE TITLE
AttributeError: module 'theano' has no attribute 'gof'

### ISSUE THREAD

**Issue by luqiang6q** [itdxer/neupy#211]
when running this code : from neupy import algorithms, estimators, environment, it occurs that AttributeError: module 'theano' has no attribute 'gof'

**Comment by itdxer** [comment]
What `neupy`, `theano` and `python` versions do you use?

```
$ python -c "import neupy,theano,platform;print(neupy.__version__, theano.__version__, platform.python_version_tuple())"
```

**Comment by itdxer** [comment]
@luqiang6q did you manage to solve your problem?

**Comment by itdxer** [comment]
@luqiang6q I cannot reproduce this issue and I will have to close it, since there is no response from you for more than 10 days.
