### ISSUE TITLE
Specify what number of input units denote in SOM documentation

### ISSUE THREAD

**Issue by ace-racer** [itdxer/neupy#214]
It would be useful for a reader reading the documentation for a specific algorithm like that for [SOM](http://neupy.com/apidocs/neupy.algorithms.competitive.sofm.html) to know that <b>n_inputs</b> denotes the number of features (columns) in the input data. The current documentation does not make this explicit.

**Comment by itdxer** [comment]
Updated: http://neupy.com/apidocs/neupy.algorithms.competitive.sofm.html#neupy.algorithms.competitive.sofm.SOFM
