### ISSUE TITLE
iter_neighbours in sofm_heatmap_visualization.py

### ISSUE THREAD

**Issue by whfarrand05** [itdxer/neupy#215]
I'm new to python, but I'm trying to get the SOFM functionality in neupy going. In trying to run the sofm_heatmap_visualization.py example, it dies at the "from utils import iter_neighbours" step because "iter_neighbours" can't be found.  In searching through the neupy sofm codes, I'm not finding it either... where is it?

**Comment by itdxer** [comment]
Hi,
It's in the same directory as `sofm_heatmap_visualization.py`: https://github.com/itdxer/neupy/tree/master/examples/competitive
https://github.com/itdxer/neupy/blob/master/examples/competitive/utils.py

**Comment by itdxer** [comment]
Works for me in python 2 and 3. Do you have somewhere file with the same name `utils.py`? Maybe in the directory from which you're trying to run this code

**Comment by whfarrand05** [comment]
Thanks for the amazingly fast response.  In my installation, the directory tree, or at least the latter part of it is: …/python3.6/site-packages/neupy/algorithms/competitive and I don’t see a utils.py in that directory.

I see the utils.py file you linked to.  Should that be in that …/neupy/algorithms/competitive directory?  I don’t know how it could have been left out of the installation, but maybe it did somehow.

Bill


On May 20, 2018, at 8:10 AM, Yurii Shevchuk <notifications@github.com<mailto:notifications@github.com>> wrote:


Works for me in python 2 and 3. Do you have somewhere file with the same name utils.py? Maybe in the directory from which you're trying to run this code

**Comment by itdxer** [comment]
The utils.py file should be in the directory with examples `examples/competitive/utils.py`. It's in the same folder as `sofm_heatmap_visualization.py`. When you write import python checks every folder available in `sys.path` looking for `utils.py`. It's possible that python import found wrong file before it reached to the `examples/competitive/`.

**Comment by whfarrand05** [comment]
OK, thanks. I think that does it…



On May 20, 2018, at 9:11 AM, Yurii Shevchuk <notifications@github.com<mailto:notifications@github.com>> wrote:


The utils.py file should be in the directory with examples examples/competitive/utils.py. It's in the same folder as sofm_heatmap_visualization.py. When you write import python checks every folder available in sys.path looking for utils.py. It's possible that python import found wrong file before it reached to the examples/competitive/.

**Comment by itdxer** [comment]
Did you manage to solve your problem?
