### ISSUE TITLE
Weights don't update

### ISSUE THREAD

**Issue by iBM88** [itdxer/neupy#218]
Line 165 from discrete_hopfield_network should change to:
self.weight = self.weight + input_data.T.dot(input_data)
from:
self.weight = input_data.T.dot(input_data)
so that the weights would update in each call of train function.

**Comment by itdxer** [comment]
Hi,
I've never used it for iterative updates and I haven't realized that this feature is broken. Thank you for pointing this out. I'll add this fix and I'll make new release.

**Comment by itdxer** [comment]
I made new release with a fix, version 0.6.5. Feel free to try it out and let me know if you have some other issues.
