### ISSUE TITLE
Problem in importing estimators for GRNN

### ISSUE THREAD

**Issue by muhammadmw** [itdxer/neupy#232]
Hello, 

i am getting the following error when starting with the GRNN algorithm.  Any help is highly appreciated. Thank you.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-9ed141b004bd> in <module>
      1 from sklearn import datasets, preprocessing
      2 from sklearn.model_selection import train_test_split
**----> 3 from neupy import algorithms, estimators**

~\Anaconda3\envs\tensorflow\lib\site-packages\neupy\estimators.py in <module>
      2 
      3 from neupy.algorithms.gd import errors
----> 4 from neupy.utils import format_data, number_type
      5 
      6 

ImportError: cannot import name 'number_type'

**Comment by muhammadmw** [comment]
just installed it today. 

**neupy-0.8.0**

**Comment by itdxer** [comment]
It's strange, since the `estimators` file has been removed since version 0.7.0 (0.6.5 was the last version that had this file). Can you try to update neupy package? You can use the following command:

```bash
conda update neupy
```

**Comment by muhammadmw** [comment]
If the `estimators` file has been removed , then it should not show up. I guess the problem is solved in that sense.

The issue was that , since I am new, I was trying the implement the GRNN code in the page where  the estimators file was imported and therefore the error occurred. So if the `estimators` file is removed, how do we do implement the code now. The link to the code is given below. [http://neupy.com/modules/generated/neupy.algorithms.GRNN.html](url)

**Comment by itdxer** [comment]
That's a good point. I think I just missed 2 places in the code examples where it's still used. I'll need to update it. Thank you for pointing this out.

**Comment by itdxer** [comment]
Example was fixed: http://neupy.com/modules/generated/neupy.algorithms.GRNN.html
