### ISSUE TITLE
cannot import name 'iter_neighbours'

### ISSUE THREAD

**Issue by NaziaFatima** [itdxer/neupy#233]
I just installed "helpers" package and trying to run sofm_heatmap_visualization.py 
It says cannot import 'iter_neighbours'

**Comment by itdxer** [comment]
Hi, I added small fix, looks like it should work now: https://github.com/itdxer/neupy/commit/e3f6ccc52f750f41294386c7a7eccfb8b916ee42

**Comment by NaziaFatima** [comment]
Hi,

It still says it can't find iter_neighbours ; @itdxer 
Please see the commands below :
```
>>> from neupy import algorithms, utils
>>> from utils import iter_neighbours
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'utils'

>>>from neupy.utils import iter_neighbours
Traceback (most recent call last):

  File "<ipython-input-31-b0ae71c523c2>", line 1, in <module>
    from neupy.utils import iter_neighbours

ImportError: cannot import name 'iter_neighbours'

```

**Comment by itdxer** [comment]
Did you move this example from the original folder somewhere else? The `utils` file should be located in the same folder as the script that tries to use it - https://github.com/itdxer/neupy/tree/master/examples/competitive

In case you didn't move it, can you show we what files do you have in the same folder with the script that you're trying to execute

**Comment by itdxer** [comment]
These issues have quite similar problem, so I'll refer to them in the original issue: 

- https://github.com/itdxer/neupy/issues/235
- https://github.com/itdxer/neupy/issues/234

**Comment by itdxer** [comment]
I just want to clarify that this `utils` file is not meant to be a part of the library, so it was separate and used only in the examples. When you try to import in from `python` REPL you need to make sure that you're in the same folder with the file `utils`.

**Comment by NaziaFatima** [comment]
Ok, I was under impression that utils.py is part of the library. 
Thanks for the clarification.
