### ISSUE TITLE
cannot import name 'iter_neighbours'

### ISSUE THREAD

**Issue by NaziaFatima** [itdxer/neupy#234]
Hi,

It still says it can't find iter_neighbours ; @itdxer
Please see the commands below :

```
>>> from neupy import algorithms, utils
>>> from utils import iter_neighbours
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'utils'

>>>from neupy.utils import iter_neighbours
Traceback (most recent call last):

  File "<ipython-input-31-b0ae71c523c2>", line 1, in <module>
    from neupy.utils import iter_neighbours

ImportError: cannot import name 'iter_neighbours'
```

**Comment by NaziaFatima** [comment]
I think the issue here is you put utils.py file in the following folder : 
neupy/examples/competitive/

which ideally should be in the following location 👍 
neupy/neupy/utils/

correct me if am mistaken.

I copied the code from that location and pasted in the sofm_heatmap_visualization.py file; it worked!!

**Comment by itdxer** [comment]
I'll close it, because this issue the same as https://github.com/itdxer/neupy/issues/233
