### ISSUE TITLE
GaussianProcess package not available

### ISSUE THREAD

**Issue by aquibjamal** [itdxer/neupy#241]
Hi,

In the Hyperparameter optimization for neural networks tutorial, the following line of code is used:
**from sklearn.gaussian_process import GaussianProcess**

Since GaussianProcess is replaced by GaussianProcessClassifier and GaussianProcessRegressor, how will the code be with GaussianProcessRegressor() function.

Please clarify this point.

Thanks in advance,

With regards,
Aquib Jamal

**Comment by itdxer** [comment]
Hi,
Thank you for reporting this issue. I've noticed this problem with new latest sklearn version and I've modified notebook, but I forgot to do the same for the article.

Notebook with modified code is available here: https://github.com/itdxer/neupy/blob/master/notebooks/Hyperparameter%20optimization%20for%20Neural%20Networks.ipynb

I hope it helps

**Comment by aquibjamal** [comment]
Thank you for the information !
