### ISSUE TITLE
Error OOM memory exhausted using lev_marq

### ISSUE THREAD

**Issue by fikri2992** [itdxer/neupy#242]
when using levemberg marquardt optimizer error OOM memory exhausted with shape[13537203,13537203]

but not with momentum with same shape

input is 45120 size with 38 dataset 
and sigmoid 300 
softmax 3
and then OOM and need fully restart on python runtime

**Comment by itdxer** [comment]
it's expected, since Levenberg-Marquardt constructs NxN matrix, where N is number of parameters

```
(45120 * 300 + 300) + (300 * 3 + 3) == 13537203
```

It's better to use LM algorithm for smaller samples and networks

**Comment by fikri2992** [comment]
wow thanks, I did not notice that I have this NVIDIA k80 to run this and still get an error 

any advice to reduce the networks if I'm still using this peripheral and iput size?

**Comment by itdxer** [comment]
you might try to reduce dimensionality of the input, maybe using PCA or SVD, if you manage to reduce it from 45120 to maybe 200 then everything should work fine.

**Comment by fikri2992** [comment]
awesome thanks, this case solved will try that PCA or SVD
