### ISSUE TITLE
The creation time of new instances of LevenbergMarquardt algorithm is not constant

### ISSUE THREAD

**Issue by andrei91ro** [itdxer/neupy#245]
First of all, my regards to the authors/contributors for sharing this great library.

Secondly, my issue arises if I try to create new instances of the `algorithms.LevenbergMarquardt` class.
After more than 10 instances, the time required to instantiate a new one starts to increase and, by the time you reach 50 or so iterations this time is on the order of 10-20 seconds.
Initially, it doesn't take more than 1 seconds to create an instance.

From my understanding of Tensorflow on GPU, it seems that each instance of LevenbergMarquard ocupies the entire GPU memory to prevent fragmentation and as new instances appear, time has to be wasted on clearing memory.

In my case, I only use one instance at a time.
I am creating multiple issues as a workaround for the fact the LM algorithm cannot be used with sklearn.GridSearchCV  because of a copy() issue (#222).
My solution was to write my own gridsearch method as @itdxer suggested in an older issue response.

I'm sharing the code in case someone needs it, and also if someone wants to test this issue on their own data:

```python
import numpy as np
from sklearn import datasets
from sklearn.model_selection import GridSearchCV
from neupy import algorithms


def do_test(train_data, train_label, val_data, val_label, mu, mu_update_factor):
    print("[do_test]", mu, mu_update_factor)
    gs_percep_lm = algorithms.LevenbergMarquardt(
        network=[
            layers.Input(x_train.shape[1]),
            layers.Sigmoid(10),
            layers.Linear(1),
        ],
        mu=float(mu),
        mu_update_factor=float(mu_update_factor),
        verbose=False,
)
    gs_percep_lm.train(train_data, train_label, val_data, val_label, epochs=5)
    return gs_percep_lm.score(x_test, y_test)

def my_grid_search(mu_val, mu_update_val, splits=3):
    cv_data = x_train.copy()
    cv_label = y_train.copy()
    kfold = KFold(n_splits=splits)
    i = 1
    score = []
    steps = splits * len(mu_val) * len(mu_update_val)
    for mu in mu_val:
        for mu_update_factor in mu_update_val:
            local_score = []
            for train_index, test_index in kfold.split(x_train):
                print ("cross validation step %d/%d" % (i, steps))

                # construct data sets
                cv_x_train, cv_x_test = cv_data[train_index], cv_data[test_index]
                cv_y_train, cv_y_test = cv_label[train_index], cv_label[test_index]
                # apply pipelines on data
                cv_x_train = seq_transformer.fit_transform(cv_x_train)
                cv_x_test = seq_transformer.transform(cv_x_test)
                cv_y_train = label_transformer.fit_transform(cv_y_train)
                cv_y_test = label_transformer.transform(cv_y_test)

                # build, train and test model and store result
                local_score.append(do_test(cv_x_train, cv_y_train, cv_x_test, cv_y_test, mu, mu_update_factor))

                i=i+1
            # end split
            score.append([
                    mu,
                    mu_update_factor,
                    np.min(local_score)
                ])
    return score
            
print("Run Grid Search CV")

result = my_grid_search([0.1, 0.5, 1, 2, 4], [1, 1.2, 4, 8])
# best = 0.5, 1.2 scor=0.0574
# result = my_grid_search([0.7], [1.2])
rez = pd.DataFrame(result, columns=["mu", "mu_update_factor", "score"])
sorted_rez = rez.sort_values(by='score')
print(sorted_rez)
```

**Comment by itdxer** [comment]
Hi @andrei91ro, I noticed this problem as well. You're right. There is a problem with Tensorflow model and creating more and more instances make it less efficient. You can apply a simple hack before creating your model. I'll need to think about some better solutions for a future versions.

Something like this should help

```python
import tensorflow as tf
from neupy.utils import tensorflow_session

for _ in range(10):  # loop is just an example of a repeat creating of the same/similar model
    tf.reset_default_graph()
    if hasattr(tensorflow_session, 'cache'):
        del tensorflow_session.cache
    model = algorithms.LevenbergMarquardt(...)  # you need to define it yourself
```

**Comment by andrei91ro** [comment]
Thank you very much, that fixed my problem.
Now, the initialization time is under one second, no matter how many times I recreate it.
The first iteration in the training loop seems to always take more than a second, but I guess that is something that also depends on my (lower-spec) hardware.
Here is an extract of the verbose log produced by the algorithm:
```
[ALGORITHM] LevenbergMarquardt

[OPTION] loss = mse
[OPTION] mu = 0.5
[OPTION] mu_update_factor = 1.2
[OPTION] show_epoch = 1
[OPTION] shuffle_data = False
[OPTION] signals = None
[OPTION] target = Tensor("placeholder/target/linear-14:0", shape=(?, 1), dtype=float32)
[OPTION] verbose = True

[TENSORFLOW] Initializing Tensorflow variables and functions.
[TENSORFLOW] Initialization finished successfully. It took 0.28 seconds
#1 : [4 sec] train: 0.205269, valid: 0.187610
#2 : [1 sec] train: 0.137850, valid: 0.220930
```

**Comment by itdxer** [comment]
First iteration is always slower since tensorflow has to create random weights. +3 seconds looks a bit too much of an overhead, but it might be justified.
