### ISSUE TITLE
The number of patterns as a feature in GRNN

### ISSUE THREAD

**Issue by jabellido94** [itdxer/neupy#268]
First, I would like to ask how the code choose the number of patterns in GRNN. Does it choose the most accurate? Is it the same as the number of inputs?

It would be great having this as a hyperparameter when defining GRNN model

**Comment by itdxer** [comment]
Hi, can you please clarify what do you mean by `number of patterns`? If you mean number of training samples that's being used during evaluation - than yes, all of the inputs will be used. I'm not aware of algorithm that allows to select a subset of inputs used for prediction in GRNN (similar to what SVM does). Do you have any references?

**Comment by jabellido94** [comment]
I think I misunderstood the GRNN architecture.
The number of nodes in the pattern layer (see attached figure) is the same as the number of training patterns ('x_train.shape[0]'), it is not chosen...

![Captura](https://user-images.githubusercontent.com/52863254/79338572-d27bc400-7f27-11ea-944a-ce050edbf31f.PNG)

**Comment by itdxer** [comment]
as far as I understand the following should be true

- Each node in the pattern layer is associated with a unique training sample (number of patterns - number of training samples). `x_train.shape[0]`
- Each node in the Input layer is associated with a specific feature which means that each input has `n` features  - `x_test.shape[1]` (`x_test.shape[1] == x_train.shape[1]`)

so I guess it just represents a standard GRNN architecture where number of pattern layers could be adjusted only be passing more/less training samples

**Comment by itdxer** [comment]
It looks to me that this issues has been resolved, but feel free to re-open it if you have some other questions
