### ISSUE TITLE
3D point cloud input

### ISSUE THREAD

**Issue by ROSNovice** [itdxer/neupy#271]
Hi @EdwardBetts @itdxer @iblech @lispyclouds @drbeco 

thanks for your impressive works.

i am interested to use neupy GNG with  3D point cloud input. is it possible for me to change the input?

Thank you

**Comment by itdxer** [comment]
Hi
I guess it depends on what do you want to do with it. If you want to input point cloud and made a single number prediction for it, then you won't be able to do it. Also, GNG is not designed to process point clouds, unless you're treating each point within the cloud independently from other points (in which case it's not longer a cloud).
