### ISSUE TITLE
module 'neupy.utils' has no attribute 'reproducible'

### ISSUE THREAD

**Issue by MohamedZaid95** [itdxer/neupy#273]
Hi I'm getting this error, any advice on how to fix it?

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-bc353d39d294> in <module>
      6 from neupy import algorithms, utils
      7 
----> 8 utils.reproducible()
      9 
     10 gng = algorithms.GrowingNeuralGas(

AttributeError: module 'neupy.utils' has no attribute 'reproducible'

**Comment by itdxer** [comment]
Can you try to import it with one of the following commands?

```
from neupy.utils import reproducible
```

or 

```
from neupy.utils.misc import reproducible
```

**Comment by MohamedZaid95** [comment]
Great! For me woreked 
`from neupy.utils.misc import reproducible`
Thank you!
