### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by dzavodnikov** [itdxer/neupy#41]
I am trying to find some license information about the project into official site and this repository, but can not. According to this link https://pypi.python.org/pypi/neupy/0.1.1 this project have MIT License.

Can you add `LICENSE` file to the repository, please?

**Comment by itdxer** [comment]
Thanks, I completely forgot about that file. I added it. You can check it here: https://github.com/itdxer/neupy/blob/master/LICENSE

**Comment by dzavodnikov** [comment]
Thanks a lot!
