### ISSUE TITLE
'Layer' object has no attribute 'activation_function'

### ISSUE THREAD

**Issue by denisvolokh** [itdxer/neupy#79]
Hi,

Here is my setup:

```python
from neupy import algorithms, layers, environment

environment.reproducible()

cgnet = algorithms.ConjugateGradient(
    connection=[
        layers.Layer(5),
        layers.Sigmoid(100),
        layers.Output(1),
    ],
    shuffle_data = False,
    show_epoch=300,
    verbose=True,
    search_method='golden',
    update_function='fletcher_reeves',
    addons=[algorithms.LinearSearch],
)
```

Do you know why I have following error:

> [THEANO] Initializing Theano variables and functions.
AttributeError: 'Layer' object has no attribute 'activation_function'

Thanks.

**Comment by itdxer** [comment]
Hi,

The `layers.Layer` class is a building block for other layer classes like, `layers.Sigmoid`, `layers.Tanh` and so on. The problem is that it doesn't have an appropriate set up for layer class. As you can see, the `activation_function` is missing. If you are using NeuP 0.2.0, you can find all possible layers in the documentation http://neupy.com/versions/0.2.0/docs/algorithms.html#layers.

So you need to replace `layers.Layer(5)` to something else. For instance `layers.Linear(5)` or `layers.Sigmoid(5)`.

I hope it will help.

**Comment by denisvolokh** [comment]
Thanks, it helped.

After changing Layer to Sigmoid I found another problem:

> ValueError: Cannot compute test value: input 0 (mean) of Op Elemwise{second,no_inplace}(mean, TensorConstant{1.0}) missing default value

I am going to update tensorflow.

**Comment by itdxer** [comment]
NeuPy is using Theano as a backend for the gradient based algorithms. You can try to remove theano directory.

```bash
$ rm -rf ~/.theano
```

And after that try to run your script again.

**Comment by denisvolokh** [comment]
Thanks again, it helped to construct network.

But now there is another problem when I train network:

> error                                     Traceback (most recent call last)
<ipython-input-20-dd75e23afb5f> in <module>()
----> 1 cgnet.train(x_train.tolist(), y_train.tolist(), x_test.tolist(), y_test.tolist(), epochs=1000)

/opt/conda/lib/python2.7/site-packages/neupy/network/constructor.pyc in train(self, input_train, target_train, input_test, target_test, *args, **kwargs)
    449             self.format_input_data(input_test),
    450             self.format_target_data(target_test),
--> 451             *args, **kwargs
    452         )
    453 

/opt/conda/lib/python2.7/site-packages/neupy/network/learning.pyc in train(self, input_train, target_train, input_test, target_test, epochs, epsilon)
     41             input_train=input_train, target_train=target_train,
     42             input_test=input_test, target_test=target_test,
---> 43             epochs=epochs, epsilon=epsilon
     44         )
     45 

/opt/conda/lib/python2.7/site-packages/neupy/network/base.pyc in train(self, input_train, target_train, input_test, target_test, epochs, epsilon)
    437         last_epoch_shown = 0
    438 
--> 439         with logs.disable_user_input():
    440             for epoch in iterepochs:
    441                 epoch_start_time = time.time()

/opt/conda/lib/python2.7/contextlib.pyc in __enter__(self)
     15     def __enter__(self):
     16         try:
---> 17             return self.gen.next()
     18         except StopIteration:
     19             raise RuntimeError("generator didn't yield")

/opt/conda/lib/python2.7/site-packages/neupy/helpers/logs.pyc in disable_user_input(self)
    171                 yield
    172             finally:
--> 173                 terminal_echo(enabled=True)
    174         else:
    175             yield

/opt/conda/lib/python2.7/site-packages/neupy/helpers/logs.pyc in terminal_echo(enabled, file_descriptor)
     31     if not is_windows:
     32         termios = importlib.import_module('termios')
---> 33         attributes = termios.tcgetattr(file_descriptor)
     34         lflag = attributes[3]
     35 

error: (25, 'Inappropriate ioctl for device')

I have same error with and without theano.

**Comment by itdxer** [comment]
That is a NeuPy bug, I need to investigate it. You can get rid of this problem just setting up parameter `verbose=False`, but you wouldn't see the training progress.

Could you tell me what OS you are using?

**Comment by denisvolokh** [comment]
I have this error on Ubuntu and OS X.

On Wednesday, 13 April 2016, Yurii Shevchuk <notifications@github.com>
wrote:

> That is a NeuPy bug, I need to investigate it. You can get rid of this
> problem just setting up parameter verbose=False, but you wouldn't see the
> training progress.
>
> Could you tell me what OS you are using?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/itdxer/neupy/issues/79#issuecomment-209352111>
>


-- 
Kind regards,
Denis Volokh

**Comment by itdxer** [comment]
Ok, I will check this issue and I will let you know.
For now you can disable verbose parameter and use signals instead to check your error after each epoch. You can find more information here: http://neupy.com/docs/secondary/signals.html

**Comment by denisvolokh** [comment]
Even if i disable verbose parameter there is same error.

Will wait for your fix.

Thanks.

Kind regards,
Denis Volokh

**Comment by itdxer** [comment]
I've added an update and pushed it in the `issue_79_termios_error_25` branch. Could you please check whether it works for you?

**Comment by denisvolokh** [comment]
Yes, it works.

Thank you.

Kind regards,
Denis Volokh
